
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-11T11:13:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d2a7a2b11deece6e0fc3faec36cafa6943a41a3",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
