
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-07T23:24:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "73ab099c0a3d7d68cfb3e785a4271a7e44447833",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
