export DOT="$HOME/dotfiles"
export ZSH_DIR="$DOT/.zsh"
export BUNDLE_DIR="$DOT/.bundle"
export GITHUB_DIR="$DOT/.github"
export ALIASES_DIR="$DOT/.aliases"
export OSINT_DIR="$DOT/.widgets/OSINT-TOOLS-CLI"
export BAT_CONFIG_PATH="$DOT/.config/bat/bat.conf"
export NU_CONFIG_PATH="$DOT/.config/nushell/config.nu"
export STARSHIP_CONFIG="$DOT/.config/starship/starship.toml"

source "$HOME/.cargo/env"
