alias neo1='neofetch --iterm2 $DOT/.config/neofetch/darkarmy.jpg'
alias neo2='neofetch --jp2a $DOT/.config/neofetch/darkarmy.jpg'
alias neo3='neofetch --caca $DOT/.config/neofetch/darkarmy.jpg'
alias neo4='neofetch --jp2a $DOT/.assets/darkarmy.jpg'
alias neo5='clear && neofetch --source $DOT/.config/neofetch/pepe.txt'