# name: reviewdog
# on: [pull_request]
# jobs:
#   reviewdog:
#     name: reviewdog
#     runs-on: ubuntu-latest
#     steps:
#       # ...
#       - uses: reviewdog/action-setup@v1
#         with:
#           reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
#       - name: Run reviewdog
#         env:
#           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.OCAT_TOKEN }}
#         run: |
#           reviewdog -reporter=github-pr-check -runners=golint,govet
#           # or
#           reviewdog -reporter=github-pr-review -runners=golint,govet
name: Shellcheck Workflow
on: [push]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.OCAT_TOKEN }}
          reporter: github-check # Change reporter.
          path: "." # Optional.
          pattern: "*.sh" # Optional.
          exclude: "./.git/*" # Optional.
          check_all_files_with_shebangs: "false" # Optional.